#!/usr/bin/env bash

# A three-in-one game app

# The game definitions
guess() {
    local -i mynumber=$(( 1 + RANDOM % 10 ))
    read -rp "I'm thinking of a number between 1 and 10. What do you think it is? " theguess
    if (( theguess == mynumber )); then
        echo "You got it! Great Job!"; echo
    else
        echo "Nope. I was thinking of $mynumber. Try again!"; echo
    fi
    sleep 1
    choosegame
}

flip() {
    local -i mynumber=$(( RANDOM % 2 ))
    if (( mynumber == 0 )); then
        local face="HEADS"
    else
